import type { Ticket, Topic } from "../../types/domain";

export function buildKanbanDemoData(spaceId = "space-demo"): { topics: Topic[]; tickets: Ticket[] } {
  const now = new Date("2026-04-15T10:30:00Z");

  const topics: Topic[] = [
    {
      id: "topic-auth-refonte",
      space_id: spaceId,
      title: "Parcours d'authentification B2B",
      description: "Stabilisation du login et onboarding entreprise",
      status: "active",
      priority: "high",
      topic_nature: "delivery",
      color: "indigo",
      roadmap_start_date: "2026-04-10",
      roadmap_end_date: "2026-05-03",
      owner: "Lina Martin",
      teams: ["Frontend", "Platform"],
      risks: ["Dépendance SSO externe"],
      dependencies: ["IdP partenaire"],
      open_questions: ["Politique de retry OTP"],
      tags: ["auth", "b2b"],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: "topic-billing",
      space_id: spaceId,
      title: "Facturation self-service",
      description: "Gestion des plans et incidents de billing",
      status: "active",
      priority: "critical",
      topic_nature: "study_delivery",
      color: "emerald",
      roadmap_start_date: "2026-04-08",
      roadmap_end_date: "2026-05-14",
      owner: "Mehdi Rahal",
      teams: ["Backend", "Ops"],
      risks: ["Règles TVA multi-pays"],
      dependencies: ["Stripe webhook"],
      open_questions: ["Modèle d'avoirs"],
      tags: ["billing", "finance"],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
  ];

  const tickets: Ticket[] = [
    {
      id: "AUTH-184",
      topic_id: "topic-auth-refonte",
      type: "feature",
      title: "Permettre la réinitialisation de mot de passe depuis une invitation expirée avec contexte société conservé",
      description: "Le flux doit rediriger l'utilisateur dans le bon tenant après régénération du lien.",
      status: "todo",
      priority: "high",
      assignee: "Inès Renaud",
      reporter: "Lina Martin",
      tags: ["self-service", "tenant"],
      acceptance_criteria: ["Lien expiré détecté", "Tenant conservé"],
      due_date: "2026-04-22",
      estimate: 5,
      dependencies: ["AUTH-177"],
      linked_document_ids: ["DOC-22"],
      ticket_details: {
        epic: "Invitation & onboarding",
        business_need: "Réduire le taux d'échec d'activation entreprise",
      },
      created_at: "2026-04-13T08:00:00Z",
      updated_at: "2026-04-15T08:15:00Z",
    },
    {
      id: "AUTH-190",
      topic_id: "topic-auth-refonte",
      type: "bug",
      title: "Le code OTP mobile échoue après changement de fuseau horaire côté appareil Android",
      description: "Le time drift invalide le code pendant la reprise de session.",
      status: "blocked",
      priority: "critical",
      assignee: "Romain Petit",
      reporter: "Support N2",
      tags: ["otp", "android", "incident"],
      acceptance_criteria: [],
      due_date: "2026-04-18",
      estimate: 3,
      dependencies: ["SDK device clock"],
      linked_document_ids: [],
      ticket_details: {
        epic: "Sécurité d'accès",
        blocked_reason: "Attente correctif SDK partenaire Android",
      },
      created_at: "2026-04-12T09:00:00Z",
      updated_at: "2026-04-15T07:10:00Z",
    },
    {
      id: "BILL-042",
      topic_id: "topic-billing",
      type: "analysis",
      title: "Qualifier l'impact métier d'un échec de webhook Stripe sur la suspension automatique",
      description: "Documenter le comportement cible avant automatisation.",
      status: "review",
      priority: "medium",
      assignee: "Camille Rossi",
      reporter: "Mehdi Rahal",
      tags: ["stripe", "workflow"],
      acceptance_criteria: ["Scénarios métier cartographiés"],
      due_date: null,
      estimate: 2,
      dependencies: [],
      linked_document_ids: ["DOC-77", "DOC-80"],
      ticket_details: {
        epic: "Résilience billing",
        subject_to_analyze: "Webhooks perdus ou en double",
      },
      created_at: "2026-04-10T14:00:00Z",
      updated_at: "2026-04-14T16:30:00Z",
    },
    {
      id: "BILL-049",
      topic_id: "topic-billing",
      type: "task",
      title: "Créer l'observabilité minimale sur les remboursements manuels et leur latence de traitement",
      description: "Ajouter métriques et journal d'audit.",
      status: "in_progress",
      priority: "high",
      assignee: null,
      reporter: "Finance Ops",
      tags: ["monitoring", "audit", "refund"],
      acceptance_criteria: ["Dashboard ops", "Audit consultable"],
      due_date: "2026-04-20",
      estimate: 8,
      dependencies: [],
      linked_document_ids: [],
      ticket_details: {
        business_context: "Réduction du temps de diagnostic finance",
      },
      created_at: "2026-04-09T10:00:00Z",
      updated_at: "2026-04-15T09:40:00Z",
    },
  ];

  return { topics, tickets };
}
